/**
 * songs.js
 *
 * The app's songs
 */

// <!-- Karoly Nemeth | 021949144 | knemeth@myseneca.ca -->

window.songs = [
  // Martin Garrix
  {
    songId: "SID-1",
    artistId: "AID-1",
    title: "Animals",
    year: "2013",
    duration: 255,
    url: "https://www.youtube.com/watch?v=gCYcHz2k5x0",
    explicit: false,
    imageUrl: "./images/martinGarrix.jpg",
  },
  {
    songId: "SID-2",
    artistId: "AID-1",
    title: "Scared to Be Lonely (with Dua Lipa)",
    year: "2017",
    duration: 210,
    url: "https://www.youtube.com/watch?v=e2vBLd5Egnk",
    explicit: false,
    imageUrl: "./images/martinGarrix.jpg",
  },
  {
    songId: "SID-3",
    artistId: "AID-1",
    title: "There for You (with Troye Sivan)",
    year: "2017",
    duration: 220,
    url: "https://www.youtube.com/watch?v=pNNMr5glICM",
    explicit: false,
    imageUrl: "./images/martinGarrix.jpg",
  },
  {
    songId: "SID-4",
    artistId: "AID-1",
    title: "High on Life (feat. Bonn)",
    year: "2018",
    duration: 227,
    url: "https://www.youtube.com/watch?v=Lpjcm1F8tY8",
    explicit: false,
    imageUrl: "./images/martinGarrix.jpg",
  },
  {
    songId: "SID-5",
    artistId: "AID-1",
    title: "Ocean (with Khalid)",
    year: "2018",
    duration: 225,
    url: "https://www.youtube.com/watch?v=BDocp-VpCwY",
    explicit: false,
    imageUrl: "./images/martinGarrix2.jpg",
  },
  {
    songId: "SID-6",
    artistId: "AID-1",
    title: "Don't Look Down (feat. Usher)",
    year: "2015",
    duration: 214,
    url: "https://www.youtube.com/watch?v=nJSdYlAFKqA&ab_channel=MartinGarrix",
    explicit: false,
    imageUrl: "./images/martinGarrix2.jpg",
  },
  {
    songId: "SID-7",
    artistId: "AID-1",
    title: "So Far Away (with David Guetta feat. Jamie Scott & Romy Dya)",
    year: "2017",
    duration: 289,
    url: "https://www.youtube.com/watch?v=o7iL2KzDh38&ab_channel=MartinGarrix",
    explicit: false,
    imageUrl: "./images/martinGarrix2.jpg",
  },
  {
    songId: "SID-8",
    artistId: "AID-1",
    title: "Hold On & Believe (feat. The Federal Empire)",
    year: "2016",
    duration: 225,
    url: "https://www.youtube.com/watch?v=LXFZd_okfUk&ab_channel=MartinGarrix",
    explicit: false,
    imageUrl: "./images/martinGarrix2.jpg",
  },

  // Tiesto
  {
    songId: "SID-9",
    artistId: "AID-2",
    title: "Red Lights",
    year: "2014",
    duration: 227,
    url: "https://www.youtube.com/watch?v=CFF0mV24WCY&ab_channel=TiestoVEVO",
    explicit: false,
    imageUrl: "./images/tiesto2.png",
  },
  {
    songId: "SID-10",
    artistId: "AID-2",
    title: "Jackie Chan (with Dzeko feat. Preme & Post Malone)",
    year: "2018",
    duration: 196,
    url: "https://www.youtube.com/watch?v=OWz3rQQaf_Q&ab_channel=TiestoVEVO",
    explicit: false,
    imageUrl: "./images/tiesto2.png",
  },
  {
    songId: "SID-11",
    artistId: "AID-2",
    title: "Adagio for Strings",
    year: "2004",
    duration: 440,
    url: "https://www.youtube.com/watch?v=2EaE0_gQLw0&ab_channel=Ti%C3%ABsto",
    explicit: false,
    imageUrl: "./images/tiesto2.png",
  },
  {
    songId: "SID-12",
    artistId: "AID-2",
    title: "Wasted (feat. Matthew Koma)",
    year: "2014",
    duration: 227,
    url: "https://www.youtube.com/watch?v=AmEIemQfk34&ab_channel=TiestoVEVO",
    explicit: false,
    imageUrl: "./images/tiesto2.png",
  },
  {
    songId: "SID-13",
    artistId: "AID-2",
    title: "Secrets (with KSHMR feat. Vassy)",
    year: "2015",
    duration: 264,
    url: "https://www.youtube.com/watch?v=Dr1nN__-2Po",
    explicit: false,
    imageUrl: "./images/tiesto2.png",
  },

  // Avicii
  {
    songId: "SID-14",
    artistId: "AID-3",
    title: "Wake Me Up",
    year: "2013",
    duration: 247,
    url: "https://www.youtube.com/watch?v=IcrbM1l_BoI",
    explicit: false,
    imageUrl: "./images/avicii1.jpeg",
  },
  {
    songId: "SID-15",
    artistId: "AID-3",
    title: "Hey Brother",
    year: "2013",
    duration: 249,
    url: "https://www.youtube.com/watch?v=YxIiPLVR6NA",
    explicit: false,
    imageUrl: "./images/avicii1.jpeg",
  },
  {
    songId: "SID-16",
    artistId: "AID-3",
    title: "Levels",
    year: "2011",
    duration: 195,
    url: "https://www.youtube.com/watch?v=_ovdm2yX4MA",
    explicit: false,
    imageUrl: "./images/avicii1.jpeg",
  },
  {
    songId: "SID-17",
    artistId: "AID-3",
    title: "The Nights",
    year: "2014",
    duration: 180,
    url: "https://www.youtube.com/watch?v=UtF6Jej8yb4",
    explicit: false,
    imageUrl: "./images/avicii1.jpeg",
  },
  {
    songId: "SID-18",
    artistId: "AID-3",
    title: "Waiting for Love",
    year: "2015",
    duration: 230,
    url: "https://www.youtube.com/watch?v=cHHLHGNpCSA",
    explicit: false,
    imageUrl: "./images/avicii2.png",
  },
  {
    songId: "SID-19",
    artistId: "AID-3",
    title: "Without You (feat. Sandro Cavazza)",
    year: "2017",
    duration: 181,
    url: "https://www.youtube.com/watch?v=WRz2MxhAdJo&ab_channel=AviciiOfficialVEVO",
    explicit: true,
    imageUrl: "./images/avicii2.png",
  },
  {
    songId: "SID-20",
    artistId: "AID-3",
    title: "Addicted to You",
    year: "2014",
    duration: 179,
    url: "https://www.youtube.com/watch?v=Qc9c12q3mrc",
    explicit: true,
    imageUrl: "./images/avicii2.png",
  },
];
